science_categories = [
    "Physics",
    "Chemistry",
    "Biology",
    "Earth Science",
    "Astronomy",
    "Mathematics",
    "Medicine",
    "Psychology",
    "Environmental Science",
    "Engineering",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Biochemistry",
    "Physical Chemistry",
    "Analytical Chemistry",
    "Geology",
    "Meteorology",
    "Oceanography",
    "Geophysics",
    "Soil Science",
    "Astrophysics",
    "Astrobiology",
    "Galaxies",
    "Planetary Science",
    "Cosmology",
    "Algebra",
    "Geometry",
    "Statistics",
    "Calculus",
    "Logic",
    "Anatomy",
    "Physiology",
    "Genetics",
    "Molecular Biology",
    "Ecology",
    "Behavioral Psychology",
    "Clinical Psychology",
    "Cognitive Psychology",
    "Developmental Psychology",
    "Social Psychology",
    "Atmospheric Science",
    "Ecology",
    "Resource Science",
    "Environmental Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Computer Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Aerospace Engineering",
    "Fluid Mechanics",
    "Thermodynamics",
    "Quantum Mechanics",
    "Relativity",
    "Solid State Physics",
    "Bioinformatics",
    "Biotechnology",
    "Pharmacology",
    "Physical Therapy",
    "Dentistry",
    "Anthropology",
    "Sociology",
    "Cultural History",
    "Linguistics",
    "Archaeology",
    "Political Science",
    "Economics",
    "Education",
    "Cognitive Science",
    "Biotechnology",
    "Material Science",
    "Nanotechnology",
    "Nuclear Physics",
    "Optics",
    "Biophysics",
    "Microbiology",
    "Virology",
    "Botany",
    "Zoology",
    "Ethology",
    "Paleontology",
    "Immunology",
    "Neuroscience",
    "Endocrinology",
    "Oncology",
    "Cardiology",
    "Rheumatology",
    "Epidemiology",
    "Genomics",
    "Proteomics",
    "Metabolomics",
    "Enzymology",
    "Toxicology",
    "Pharmacodynamics",
    "Pharmacokinetics",
    "Mycology",
    "Parasitology",
    "Entomology",
    "Ichthyology",
    "Herpetology",
    "Ornithology",
    "Mammalogy",
    "Cytology",
    "Histology",
    "Neurology",
    "Radiology",
    "Immunohistochemistry",
    "Crystallography",
    "Petroleum Geology",
    "Seismology",
    "Volcanology",
    "Paleoclimatology",
    "Limnology",
    "Pedology",
    "Aerodynamics",
    "Quantum Chemistry",
    "Orbital Mechanics",
    "Systems Biology",
    "Computational Biology",
    "Astrochemistry",
    "Paleobotany",
    "Evolutionary Biology",
    "Marine Biology",
    "Structural Biology",
    "Neuropharmacology",
    "Biogeochemistry",
    "Quantum Computing",
    "Algorithm Theory",
    "Information Theory",
    "Human Genetics",
    "Chaos Theory",
    "Differential Equations",
    "Topology",
    "Number Theory",
    "Mathematical Logic",
    "Discrete Mathematics",
    "Stochastic Processes",
    "Dynamical Systems",
    "Mathematical Physics",
    "Combinatorics",
    "Set Theory",
    "Graph Theory",
    "Measure Theory",
    "Numerical Analysis",
    "Mathematical Biology",
    "Cryptography",
    "Game Theory",
    "Operational Research",
    "Mathematical Economics",
    "Statistical Mechanics",
]

art_categories = [
    "Painting",
    "Sculpture",
    "Drawing",
    "Printmaking",
    "Photography",
    "Film",
    "Animation",
    "Performance Art",
    "Architecture",
    "Ceramics",
    "Textile Art",
    "Digital Art",
    "Conceptual Art",
    "Installation Art",
    "Graphic Design",
    "Fashion Design",
    "Interior Design",
    "Theatre",
    "Dance",
    "Music",
    "Classical Music",
    "Jazz",
    "Rock",
    "Pop",
    "Blues",
    "Country",
    "Electronic",
    "Rap",
    "Folk",
    "World Music",
    "Abstract Art",
    "Realism",
    "Surrealism",
    "Impressionism",
    "Expressionism",
    "Cubism",
    "Minimalism",
    "Baroque",
    "Renaissance",
    "Romanticism",
    "Typography",
    "Illustration",
    "Calligraphy",
    "Collage",
    "Mosaic",
    "Street Art",
    "Graffiti",
    "Comic Art",
    "Storyboarding",
    "Web Design",
    "Art Nouveau",
    "Art Deco",
    "Pop Art",
    "Op Art",
    "Dadaism",
    "Fauvism",
    "Neoclassicism",
    "Futurism",
    "Constructivism",
    "Post-Impressionism",
    "Video Art",
    "Art Criticism",
    "Art History",
    "Art Conservation",
    "Art Restoration",
    "Art Theory",
    "Craft",
    "Mixed Media",
    "Stained Glass",
    "Silversmithing",
    "Goldsmithing",
    "Blacksmithing",
    "Metalworking",
    "Woodworking",
    "Engraving",
    "Etching",
    "Lithography",
    "Serigraphy",
    "Tapestry",
    "Weaving",
    "Ballet",
    "Contemporary Dance",
    "Hip Hop Dance",
    "Ballroom Dance",
    "Folk Dance",
    "Tap Dance",
    "Salsa",
    "Flamenco",
    "Tango",
    "Waltz",
    "Choreography",
    "Drama",
    "Comedy",
    "Tragedy",
    "Musical Theatre",
    "Opera",
    "Puppetry",
    "Mime",
    "Circus Arts",
    "Magic",
    "Pottery",
    "Documentary Photography",
    "Portrait Photography",
    "Landscape Photography",
    "Still Life",
    "Art Therapy",
    "Fashion Photography",
    "Commercial Art",
    "Branding",
    "Logo Design",
    "Industrial Design",
    "Jewelry Design",
    "Bookbinding",
    "Book Arts",
    "Papermaking",
    "Letterpress",
    "Paper Cutting",
    "Origami",
    "3D Modeling",
    "Digital Illustration",
    "Pixel Art",
    "Virtual Reality Art",
    "Interactive Art",
    "Game Design",
    "Sound Art",
    "Folk Art",
    "Indigenous Art",
    "Art Festivals",
    "Art Galleries",
    "Art Museums",
    "Art Collecting",
    "Art Auctions",
    "Public Art",
    "Monument Design",
    "Mural Painting",
    "Caricature",
    "Anime",
    "Manga",
    "Storyboard Art",
    "Concept Art",
    "Ink Painting",
    "Pastel Art",
    "Charcoal Drawing",
    "Acrylics",
    "Watercolor",
    "Oil Painting",
    "Gouache",
    "Plein Air Painting",
    "Art Education",
    "Art Workshops",
    "Fashion Illustration",
    "Costume Design",
    "Set Design",
    "Lighting Design",
    "Makeup Artistry",
    "Tattoo Artistry",
    "Body Art",
    "Performance Poetry",
    "Spoken Word",
    "Art Journalism",
]

history_categories = [
    "Ancient History",
    "Medieval History",
    "Modern History",
    "Contemporary History",
    "Cultural History",
    "Economic History",
    "Intellectual History",
    "Military History",
    "Political History",
    "Social History",
    "African History",
    "American History",
    "Asian History",
    "European History",
    "Oceanian History",
    "Middle Eastern History",
    "Latin American History",
    "Caribbean History",
    "Central Asian History",
    "South Asian History",
    "Ancient Egypt",
    "Ancient Greece",
    "Ancient Rome",
    "Viking Age",
    "Renaissance",
    "Enlightenment",
    "Industrial Revolution",
    "World War I",
    "World War II",
    "Cold War",
    "Biblical History",
    "Islamic History",
    "Buddhist History",
    "Hindu History",
    "Chinese Dynasties",
    "Japanese Shogunate",
    "Mongol Empire",
    "Ottoman Empire",
    "Mughal Empire",
    "British Empire",
    "Colonial History",
    "Revolutionary History",
    "Slavery History",
    "Holocaust Studies",
    "Genocide Studies",
    "Civil Rights Movement",
    "Feminist History",
    "Environmental History",
    "History of Science",
    "History of Technology",
    "Archaeology",
    "Paleography",
    "Historiography",
    "Oral History",
    "Public History",
    "Diplomatic History",
    "History of Ideas",
    "Legal History",
    "Art History",
    "Literary History",
    "History of Religion",
    "History of Philosophy",
    "History of Medicine",
    "History of Mathematics",
    "History of Music",
    "History of Film",
    "History of Theatre",
    "History of Fashion",
    "History of Sports",
    "History of Food",
    "Prehistoric Age",
    "Stone Age",
    "Bronze Age",
    "Iron Age",
    "Age of Discovery",
    "Age of Imperialism",
    "Digital Age",
    "Space Age",
    "Nuclear Age",
    "Information Age",
    "Native American History",
    "Byzantine History",
    "Soviet History",
    "Napoleonic Era",
    "Victorian Era",
    "American Civil War",
    "French Revolution",
    "Russian Revolution",
    "Chinese Revolution",
    "Reformation",
    "Crusades",
    "Silk Road",
    "Colonization of Africa",
    "Spanish Conquest",
    "American Frontier",
    "Transatlantic Slave Trade",
    "Pax Romana",
    "Meiji Restoration",
    "Belle Époque",
    "Roaring Twenties",
    "Great Depression",
    "Rise of Fascism",
    "Decolonization",
    "European Union History",
    "ASEAN History",
    "UN History",
    "NATO History",
    "Treaty of Versailles",
    "Renaissance Humanism",
    "Protestant Reformation",
    "Mesoamerican History",
    "Inca Civilization",
    "Aztec Civilization",
    "Maya Civilization",
    "Indus Valley Civilization",
    "Mesopotamian Civilization",
    "Han Dynasty",
    "Roman Republic",
    "Roman Empire",
    "Achaemenid Empire",
    "Babylonian Empire",
    "Assyrian Empire",
    "Hittite Empire",
    "Pharaohs of Egypt",
    "Alexander the Great",
    "Golden Age of Piracy",
    "Tudor Period",
    "Stuart Period",
    "Bourbon Dynasty",
    "Habsburg Dynasty",
    "Norman Conquest",
    "Hundred Years' War",
    "Thirty Years' War",
    "Boer Wars",
    "Vietnam War",
    "Korean War",
    "American Revolution",
    "Punic Wars",
    "Peloponnesian War",
    "Gulf Wars",
    "War on Terror",
    "Arab-Israeli Conflict",
    "India's Freedom Struggle",
    "Great Schism",
    "Migration Period",
    "Gilded Age",
    "Progressive Era",
    "Antebellum Period",
    "Reconstruction Era",
    "Age of Enlightenment",
    "Rise of Christianity",
    "Gothic Period",
    "Baroque Period",
    "Romantic Period",
    "Neoclassical Period",
    "Edwardian Era",
    "Regency Era",
    "Interwar Period",
    "Post-war Era",
    "Age of Exploration",
]

literature_categories = [
    "Novel",
    "Short Story",
    "Poetry",
    "Drama",
    "Essay",
    "Biography",
    "Autobiography",
    "Memoir",
    "Epic",
    "Lyric",
    "Tragedy",
    "Comedy",
    "Satire",
    "Parody",
    "Romance",
    "Mystery",
    "Fantasy",
    "Science Fiction",
    "Horror",
    "Historical Fiction",
    "Young Adult",
    "Children's Literature",
    "Graphic Novel",
    "Adventure",
    "Mythology",
    "Fairy Tale",
    "Folklore",
    "Allegory",
    "Fable",
    "Dystopian",
    "Utopian",
    "Realism",
    "Surrealism",
    "Postmodernism",
    "Modernism",
    "Gothic",
    "Pulp Fiction",
    "Travelogue",
    "Bildungsroman",
    "Picaresque",
    "Metafiction",
    "Epistolary",
    "Stream of Consciousness",
    "Magical Realism",
    "Cyberpunk",
    "Steampunk",
    "Neorealism",
    "Fantasy of Manners",
    "Dieselpunk",
    "Sword and Sorcery",
    "Hard Science Fiction",
    "Space Opera",
    "Post-Apocalyptic",
    "Speculative Fiction",
    "Romanticism",
    "Naturalism",
    "Existentialism",
    "Absurdism",
    "Symbolism",
    "Transcendentalism",
    "Beat Generation",
    "Harlem Renaissance",
    "Victorian Literature",
    "Elizabethan Era",
    "Medieval Literature",
    "Classical Literature",
    "Renaissance Literature",
    "Neo-Classical Literature",
    "Literary Criticism",
    "Literary Theory",
    "Feminist Literature",
    "LGBTQ+ Literature",
    "Post-colonial Literature",
    "African Literature",
    "Asian Literature",
    "European Literature",
    "American Literature",
    "Middle Eastern Literature",
    "Latin American Literature",
    "Russian Literature",
    "Slavic Literature",
    "Nordic Literature",
    "Oral Tradition",
    "Epic Poetry",
    "Sonnet",
    "Haiku",
    "Limerick",
    "Ballad",
    "Ode",
    "Elegy",
    "Pastoral",
    "Villanelle",
    "Sestina",
    "Free Verse",
    "Blank Verse",
    "Ghazal",
    "Tanka",
    "Renga",
    "Prose Poetry",
    "Narrative Poetry",
    "Crime Fiction",
    "Spy Fiction",
    "Thriller",
    "Western",
    "Urban Fantasy",
    "Dark Fantasy",
    "Erotic Fiction",
    "Religious Fiction",
    "Philosophical Fiction",
    "Alternate History",
    "Paranormal Romance",
    "Literary Fiction",
    "Fan Fiction",
    "Academic Writing",
    "Journalism",
    "Op-ed",
    "Anthology",
    "Literary Journal",
    "Historical Romance",
    "Military Fiction",
    "Literary Nonfiction",
    "Creative Nonfiction",
    "Inspirational Fiction",
    "Diary",
    "Mystical Fiction",
    "Classic Literature",
    "Flash Fiction",
    "Micro Fiction",
    "Fan Fiction",
    "Science Fantasy",
    "Noir",
    "Hardboiled Fiction",
    "Regency Romance",
    "Period Drama",
    "Martial Arts Fiction",
    "Experimental Fiction",
    "Epigram",
    "Dirge",
    "Eclogue",
    "Dramedy",
    "Monologue",
    "Soliloquy",
    "One-act Play",
    "Tragicomedy",
    "Farse",
    "Melodrama",
    "Moral Tale",
    "Mock Epic",
    "Pastoral Elegy",
    "Acrostic",
    "Clerihew",
    "Concrete Poetry",
    "Didactic Poetry",
    "Dramatic Monologue",
    "Verse Novel",
    "Verse Drama",
    "Heroic Couplets",
    "Aphorism",
    "Maxim",
    "Feminist Science Fiction",
]

social_sciences_categories = [
    "Anthropology",
    "Sociology",
    "Psychology",
    "Political Science",
    "Economics",
    "Geography",
    "History",
    "Law",
    "Criminology",
    "Linguistics",
    "Cultural Studies",
    "Gender Studies",
    "Ethnic Studies",
    "Public Administration",
    "International Relations",
    "Human Geography",
    "Physical Geography",
    "Urban Studies",
    "Rural Studies",
    "Environmental Studies",
    "Behavioral Science",
    "Social Psychology",
    "Clinical Psychology",
    "Cognitive Psychology",
    "Developmental Psychology",
    "Neuropsychology",
    "Forensic Psychology",
    "Health Psychology",
    "Educational Psychology",
    "Sport Psychology",
    "Microeconomics",
    "Macroeconomics",
    "Behavioral Economics",
    "Econometrics",
    "Development Economics",
    "Environmental Economics",
    "Labor Economics",
    "Public Economics",
    "Health Economics",
    "Financial Economics",
    "Constitutional Law",
    "Criminal Law",
    "Civil Law",
    "Corporate Law",
    "International Law",
    "Human Rights Law",
    "Environmental Law",
    "Family Law",
    "Tax Law",
    "Intellectual Property Law",
    "Archaeology",
    "Human Evolution",
    "Cultural Anthropology",
    "Linguistic Anthropology",
    "Physical Anthropology",
    "Social Anthropology",
    "Ethnography",
    "Ethnology",
    "Paleoanthropology",
    "Forensic Anthropology",
    "Political Theory",
    "Comparative Politics",
    "Public Policy",
    "Political Economy",
    "Political Philosophy",
    "Public Law",
    "International Politics",
    "Political Behavior",
    "Political Institutions",
    "Political Methodology",
    "Social Theory",
    "Social Research",
    "Social Stratification",
    "Social Movements",
    "Social Networks",
    "Family Studies",
    "Population Studies",
    "Religion and Society",
    "Crime and Society",
    "Work and Occupations",
    "Human Rights",
    "Conflict Resolution",
    "Terrorism Studies",
    "Peace Studies",
    "Diplomacy",
    "Geopolitics",
    "Globalization",
    "Migration Studies",
    "Nationalism Studies",
    "Development Studies",
    "Urban Sociology",
    "Sociology of Health",
    "Sociology of Education",
    "Rural Sociology",
    "Sociology of Religion",
    "Sociology of Gender",
    "Sociology of Race",
    "Sociology of Age",
    "Sociology of Sport",
    "Environmental Sociology",
    "Media Studies",
    "Communication Studies",
    "Film Studies",
    "Journalism",
    "Public Relations",
    "Advertising",
    "Broadcasting",
    "Digital Media",
    "Media Criticism",
    "Mass Communication",
    "Human Ecology",
    "Demography",
    "Cartography",
    "Geomatics",
    "Remote Sensing",
    "GIS (Geographic Information Systems)",
    "Cultural Geography",
    "Economic Geography",
    "Political Geography",
    "Transport Geography",
    "Child Studies",
    "Adolescent Studies",
    "Elderly Studies",
    "Family Dynamics",
    "Sexuality Studies",
    "Subcultures",
    "Community Studies",
    "Public Health",
    "Social Work",
    "Educational Administration",
    "Philosophy of Law",
    "Philosophy of Economics",
    "Philosophy of Education",
    "Philosophy of History",
    "Philosophy of Politics",
    "Consumer Behavior",
    "Social Change",
    "Inequality",
    "Social Integration",
    "Social Control",
    "Public Opinion",
    "Quantitative Research",
    "Qualitative Research",
    "Mixed Methods Research",
    "Social Experimentation",
    "Case Studies",
    "Comparative Analysis",
    "Content Analysis",
    "Field Research",
    "Historical Analysis",
]
