name: 배포

on:
  push:
    branches:
      - main

jobs:

  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'


    steps:
      - uses: actions/checkout@v2

      - name: create dotenv
        run: echo "${{ secrets.ENV }}" > .env

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          docker build -f Dockerfile .\
            -t ghcr.io/gooroomee-alpha/sat_gpt_generator/sat-generator:${GITHUB_SHA}\
            -t ghcr.io/gooroomee-alpha/sat_gpt_generator/sat-generator:latest
      - name: Push image
        run: |
          docker push ghcr.io/gooroomee-alpha/sat_gpt_generator/sat-generator:${GITHUB_SHA}
          docker push ghcr.io/gooroomee-alpha/sat_gpt_generator/sat-generator:latest
  deploy:
    needs: push
    name: 배포
    runs-on: [ self-hosted ]
    steps:
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker compose up
        run: SHA=${GITHUB_SHA} docker compose -f ~/docker-compose.yml up -d generate-sat-backend